project_id = "rtjxurmuaawyzjcdkqxt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[analytics]
enabled = false

[functions.line-webhook]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.scenario-invite]
verify_jwt = false

[functions.login-callback]
verify_jwt = false

[functions.scenario-login]
verify_jwt = false

[functions.liff-handler]
verify_jwt = false

[functions.trigger-scenario]
verify_jwt = false

[functions.scheduled-step-delivery]
verify_jwt = false

[functions.enhanced-step-delivery]
verify_jwt = false

[functions.delete-form]
verify_jwt = true

[functions.cms-page-view]
verify_jwt = false

[functions.public-get-product]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-product]
verify_jwt = true

[functions.update-stripe-product]
verify_jwt = true

[functions.stripe-refund]
verify_jwt = true

[functions.member-site-view]
verify_jwt = false

[functions.member-site-progress]
verify_jwt = false

[functions.liff-rich-menu-redirect]
verify_jwt = false
