project_id = "rtjxurmuaawyzjcdkqxt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[analytics]
enabled = false

[functions.line-webhook]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.scenario-invite]
verify_jwt = false

[functions.login-callback]
verify_jwt = false